server:
  port: 8764

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: service-ribbon
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer:
      retry:
        enabled: true

ribbon:
  ReadTimeout: 2000  #默认值2000
  ConnectTimeout: 2000 #默认值5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #默认值1000

