server:
  port: 8766

eureka:
  client:
  service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: service-zuul
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
      sampler:
        percentage: 1
zuul:
  routes:
    api-a:
        path: /api-ribbon/**
        serviceId: service-ribbon
    api-b:
        path: /api-feign/**
        serviceId: service-feign






