server:
  port: 8763

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: service-user2
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1
